### PR TITLE
Add support for `nothing`

### PR DESCRIPTION
**Pull request by simsurace**
I have been using this quite often to conditionally drop specific parameters, and I'm considering using it in a public package. Since it is piracy to define it elsewhere, I would kindly ask to consider adding this here. I will add a test if this doesn't raise any fundamental concerns.

### CODE REVIEW

**Comment by willtebbutt** [comment]
I can't see anything to be concerned about -- I can definitely get behind this. I'm happy to approve once you've added the test cases that you mention.

**Review by willtebbutt — APPROVED** [review]
LGTM. Thanks for the contribution

**Comment by willtebbutt** [comment]
Do you merge rights @simsurace ?

**Comment by simsurace** [comment]
BTW, why is CI not running?

**Comment by willtebbutt** [comment]
Ooooo I did not twig that that had no happened. I'll check.

**Pull request merged**
